/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  important: true,
  theme: {
    extend: {
      spacing: {
        112: '28rem',
        128: '32rem',
        header: 'var(--header_height)',
        header_notification: 'var(--header_notification)',
        sidebar: 'var(--sidebar_width)',
        sidebarSmall: 'var(--sidebar_width_small)',
      },
      colors: {
        primary: 'var(--primary_color)',
        secondary: 'var(--secondary_color)',
        tertiary_color: 'var(--tertiary_color)',
        text_color: 'var(--text_color)',
        primary01_color: 'var(--primary01)',
        neutrals01_color: 'var(--neutrals01)',
        neutrals02_color: 'var(--neutrals02)',
        neutrals03_color: 'var(--neutrals03)',
        neutrals04_color: 'var(--neutrals04)',
        neutrals05_color: 'var(--neutrals05)',
        neutrals06_color: 'var(--neutrals06)',
        neutrals07_color: 'var(--neutrals07)',
        neutrals08_color: 'var(--neutrals08)',
        neutrals09_color: 'var(--neutrals09)',
        primary02_color: 'var(--primary02)',
        primary03_color: 'var(--primary03)',
        other01_color: 'var(--other01)',
        other02_color: 'var(--other02)',
        other03_color: 'var(--other03)',
        other04_color: 'var(--other04)',
        other_gradient01_color: 'var(--other_gradient01)',
        other_gradient02_color: 'var(--other_gradient02)',
        other_gradient03_color: 'var(--other_gradient03)',
        other_gradient04_color: 'var(--other_gradient04)',
      },
      backgroundColor: {
        primary_color: 'var(--primary_color)',
        secondary_color: 'var(--secondary_color)',
        active_color: 'var(--active_color)',
        icon_active_color: 'var(--icon_active_color)',
        tertiary: 'var(--tertiary_color)',
        navbar: 'var(--table_row_even_color)',
        hover_navbar: 'rgba(255,255,255,0.4)',
        table_header: 'var(--table_header_color)',
        search_table_header: 'var(--search_table_color)',
        table_row_odd: 'var(--table_row_odd_color)',
        table_row_even: 'var(--table_row_even_color)',
        row_hover_color: 'var(--row_hover_color)',
        row_focus_color: 'var(--row_focus_color)',
        primary01_color: 'var(--primary01)',
        primary02_color: 'var(--primary02)',
        primary03_color: 'var(--primary03)',
        other01_color: 'var(--other01)',
        other02_color: 'var(--other02)',
        other03_color: 'var(--other03)',
        other04_color: 'var(--other04)',
        other_gradient01_color: 'var(--other_gradient01)',
        other_gradient02_color: 'var(--other_gradient02)',
        other_gradient03_color: 'var(--other_gradient03)',
        other_gradient04_color: 'var(--other_gradient04)',
        semi_transparent: 'var(--semi_transparent)',
      },
      borderWidth: {
        0.5: '0.0625rem',
        16: '0.8rem',
      },
      borderColor: {
        navbar: 'var(--table_row_even_color)',
      },
      flexBasis: {
        '1/7': '14.2857143%',
        '2/7': '28.5714286%',
        '3/7': '42.8571429%',
        '4/7': '57.1428571%',
        '5/7': '71.4285714%',
        '6/7': '85.7142857%',

        '1/10': '10%',
        '2/10': '20%',
        '3/10': '30%',
        '4/10': '40%',
        '5/10': '50%',
        '6/10': '60%',
        '7/10': '70%',
        '8/10': '80%',
        '9/10': '90%',

        '1/8': '12.5%',
        '2/8': '25%',
        '3/8': '37.5%',
        '4/8': '50%',
        '5/8': '62.5%',
        '6/8': '75%',
        '7/8': '87.5%',
      },
      zIndex: {
        999: '999',
      },
      fontSize: {
        small: '0.8rem',
        medium: '0.875rem',
        large: '1rem',
        title: '1.125rem',
      },
      minWidth: {
        button: '120px',
        button_small: '80px',
      },
      minHeight: {
        button: '36px',
        button_small: '28px',
      },
      width: {
        5.5: '1.375rem',
        34: '8.5rem',
        35: '8.75rem',
        sidebar_width: 'var(--sidebar_width)',
        sidebar_width_small: 'var(--sidebar_width_small)',
      },
      height: {
        5.5: '1.375rem',
        18: '4.5rem',
        'header-content': '3.375rem',
        table_header_height: 'var(--table_header_height)',
        table_search_height: 'var(--table_search_height)',
        table_row_height: 'var(--table_row_height)',
        header_height: 'var(--header_height)',
        content_sidebar: 'var(--content_sidebar)',
        header_height_small: 'var(--header_height_small)',
        footer_height: 'var(--footer_height)',
        header_notification: 'var(--header_notification)',
      },
      maxHeight: {
        header: 'var(--header_height)',
        header_notification: 'var(--header_notification)',
        18: '4.5rem',
      },
    },
  },
  plugins: [],
};
