export const TABLE_TYPE = {
    CUSTOMER_SEARCH: 0,
    IMEI_SEARCH_BY_IMEI: 1,
    IMEI_SEARCH_BY_MERCHANDISE: 2,
    DELIVERY_SEARCH: 3,
    MERCHANDISE_LIST: 4,
    DISCOUNT_LIST: 5,
    SERVICE_LIST: 6,
    GUARANTEE_LIST: 7
}